using HabitTracker.Api.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HabitTracker.Api.Data.Configurations;

public class HabitConfiguration : IEntityTypeConfiguration<Habit>
{
    public void Configure(EntityTypeBuilder<Habit> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("habits");

        builder.HasKey(h => h.Id);

        // Primary key configuration: client-generated UUIDs, never regenerated by the database
        builder.Property(h => h.Id)
            .ValueGeneratedNever();

        // User relationship: each habit belongs to a user (FK added when User entity is implemented)
        builder.Property(h => h.UserId)
            .IsRequired();

        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(h => h.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // Habit metadata
        builder.Property(h => h.Name)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(h => h.Description)
            .HasMaxLength(2000);

        builder.Property(h => h.Type)
            .IsRequired();

        builder.Property(h => h.Status)
            .IsRequired();

        // Owned types: Frequency (required, non-nullable)
        builder.OwnsOne(h => h.Frequency, frequency =>
        {
            frequency.Property(f => f.Type)
                .HasColumnName("frequency_type")
                .IsRequired();

            frequency.Property(f => f.TimesPerPeriod)
                .HasColumnName("frequency_times_per_period")
                .IsRequired();
        });

        // Owned types: Target (required, non-nullable; both Value and Unit can be individually null for binary habits)
        builder.OwnsOne(h => h.Target, target =>
        {
            target.Property(t => t.Value)
                .HasColumnName("target_value");

            target.Property(t => t.Unit)
                .HasColumnName("target_unit")
                .HasMaxLength(100);
        });

        // Owned types: Milestone (required, non-nullable)
        builder.OwnsOne(h => h.Milestone, milestone =>
        {
            milestone.Property(m => m.Target)
                .HasColumnName("milestone_target")
                .IsRequired();

            milestone.Property(m => m.Current)
                .HasColumnName("milestone_current")
                .IsRequired();
        });

        // Optional reminder time
        builder.Property(h => h.ReminderTime)
            .HasColumnName("reminder_time");

        // Streak tracking
        builder.Property(h => h.CurrentStreak)
            .HasColumnName("current_streak")
            .HasDefaultValue(0);

        builder.Property(h => h.LongestStreak)
            .HasColumnName("longest_streak")
            .HasDefaultValue(0);

        builder.Property(h => h.LastStreakBrokenAt)
            .HasColumnName("last_streak_broken_at");

        // Archive tracking
        builder.Property(h => h.IsArchived)
            .HasColumnName("is_archived")
            .HasDefaultValue(false);

        builder.Property(h => h.ArchivedAt)
            .HasColumnName("archived_at");

        builder.Property(h => h.EndDate)
            .HasColumnName("end_date");

        // Audit timestamps (always stored in UTC)
        builder.Property(h => h.CreatedAtUtc)
            .IsRequired()
            .HasColumnType("timestamp with time zone");

        builder.Property(h => h.UpdatedAtUtc)
            .HasColumnType("timestamp with time zone");

        builder.Property(h => h.LastCompletedAtUtc)
            .HasColumnType("timestamp with time zone");
    }
}