using HabitTracker.Api.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HabitTracker.Api.Data.Configurations;

public class TagConfiguration : IEntityTypeConfiguration<Tag>
{
    public void Configure(EntityTypeBuilder<Tag> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("tags");

        builder.HasKey(t => t.Id);

        // Primary key configuration: client-generated UUIDs, never regenerated by the database
        builder.Property(t => t.Id)
            .ValueGeneratedNever();

        // User relationship
        builder.Property(t => t.UserId)
            .IsRequired();

        // Tag name: required, max 50 characters
        builder.Property(t => t.Name)
            .IsRequired()
            .HasMaxLength(50);

        // Unique constraint on (UserId, Name) to ensure tag name uniqueness per user
        builder.HasIndex(t => new { t.UserId, t.Name })
            .IsUnique();

        // Timestamps
        builder.Property(t => t.CreatedAtUtc)
            .IsRequired();

        builder.Property(t => t.UpdatedAtUtc);

        // Navigation property for many-to-many relationship
        builder.HasMany(t => t.HabitTags)
            .WithOne(ht => ht.Tag)
            .HasForeignKey(ht => ht.TagId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
